- lib/pages/editProfile.dart
- lib/pages/signin.dart
Just fixed the keyboard overflow and add the app bar!
> fixed keyboard overflow and added app bar

- lib/pages/forgotpassword.dart
- lib/pages/login.dart
- lib/pages/signup.dart
fixed entering password in signup and login.dart to prevent leading or trailing whitespaces
> fixed whitespaces in password

- lib/main.dart
- lib/models/user.dart
- lib/pages/createProfile.dart
- lib/pages/myProfile.dart
- lib/pages/navigationHome.dart
- lib/services/database.dart
Main changes in user.dart, myProfile.dart and createProfile.dart
> Display user data from db in profile

- lib/pages/myProfile.dart
- lib/pages/profilePreview.dart
- lib/pages/uploadphoto.dart
Main changes in profilePreview.dart
> Pulling data from db and displaying it in preview profile

- TODO.md
- lib/pages/uploadphoto.dart
Photo upload working, also receiving the URL to the photo in the same function.
> Photo storage

- lib/main.dart
- lib/models/user.dart
- lib/pages/createProfile.dart
- lib/pages/match.dart
- lib/pages/message.dart
- lib/pages/profilePreview.dart
- lib/services/database.dart
Most changes made on match.dart file
> Completed match logic

- lib/main.dart
- lib/pages/getMatch.dart
- lib/pages/match.dart
- lib/pages/messagesList.dart
- lib/pages/wrapper.dart
- If matches == 0, you should see a get your new match button on match page
> Moved limit matches logic to matches.dart 

- .gitignore
- lib/main.dart
- lib/pages/editProfile.dart
- lib/pages/match.dart
- lib/pages/message.dart
- lib/pages/messagesList.dart
- lib/pages/myProfile.dart
- lib/pages/navigationHome.dart
- lib/pages/profilePreview.dart
- lib/pages/signin.dart
- lib/pages/welcome.dart
- lib/services/database.dart
edit profile now updates the db with new values BUT still needs work:
- drop down values need to be filled with original values
- chips need to be highlighted with original true/false
> Edit profile updates the the db

- lib/main.dart
- lib/pages/editProfile.dart
- lib/pages/match.dart
- lib/pages/message.dart
- lib/pages/myProfile.dart
- lib/pages/preferences.dart
- edit profile save button routes you to myProfile
- added nickname and imgurl to arguments to Message() in match.dart
- didn't make changes to message.dart (I think it just reformatted the code)
- myProfile no longer uses streambuilder because navigationHome provides userData
- added preferences.dart and routes
- logout should not throw errors anymore
> Bug fixes and small changes

- lib/main.dart
- lib/models/user.dart
- lib/pages/createProfile.dart
- lib/pages/match.dart
- lib/pages/myProfile.dart
- lib/pages/profile.dart
- lib/pages/profilePreview.dart
- lib/pages/questions.dart
- lib/services/database.dart
Added questions to signup flow
Preview questions/answers in profile preview
See questions/answers in myprofile, profile and match files
questions in the signupflow
match.dart profile
myprofile.dart
profile.dart
> Questions functionality completed

- lib/pages/message.dart
- lib/pages/profile.dart
- lib/pages/questions.dart
The blur values are being pulled from the db and used to control the blur filter in profile.dart
> Completed blur functionality

- lib/main.dart
- lib/pages/questions.dart
- pubspec.lock
- pubspec.yaml
no limit to text field and prevent overlapping of form label and input field
> Fixed UI bugs in question form

- lib/main.dart
- lib/pages/editPhoto.dart
- lib/pages/editProfile.dart
- lib/pages/match.dart
- lib/pages/messagesList.dart
- lib/pages/myProfile.dart
- lib/pages/profile.dart
- lib/shared/loading.dart
- You can now edit photos by clicking on the circle avatar in editprofile. It reroutes you to navigationHome at the moment since I couldn't figure out how to reroute it back to editProfile since editProfile requires you provide arguments
- messagesList is now reading blur values from the db
- changed loading heart to orange color
- match with new users when you click "meet someone new" in match.dart but preference filter is not applied
> edit photo, unblur on messagelist, loading heart color, match new users

- lib/pages/editProfile.dart
- lib/pages/myProfile.dart
was writing null to the db in previous push when you didn't change preference values but fixed that.
Age range still defaults to 18-100 but can't figure out how to work around
> fixed a bug for RangeSlider

- lib/pages/editPhoto.dart
- lib/pages/editProfile.dart
- lib/pages/match.dart
- lib/pages/moreQuestions.dart
- lib/pages/myProfile.dart
- lib/pages/profile.dart
- lib/pages/questions.dart
- lib/services/database.dart
added emojis to all questions, ability to edit and answer all questions, rerouted editing to the correct place thanks to Yuya's awesome routing and fixed profile spacing bug
> Completed everything to do with questions

- lib/main.dart
- lib/pages/match.dart
- lib/pages/navigationHome.dart
- lib/pages/uploadphoto.dart
- pubspec.lock
- pubspec.yaml
Most of them are "fade", so you won't see the dynamic transition, I think
> added animated transition to page

- lib/pages/match.dart
- lib/pages/message.dart
[new route]
match.dart -> select "send 🍺" -> message.dart -> messagelist.dart
[old route]
match.dart -> select "send 🍺" -> message.dart -> match.dart
> Changed routing 

- lib/pages/match.dart
- lib/pages/myProfile.dart
- lib/pages/profile.dart
And added overflow fix to profile.dart
> added horizontal scroll for interests

- lib/pages/match.dart
- lib/pages/myProfile.dart
> Pimped up the chat button and answer mo q buttons

- lib/pages/match.dart
- lib/pages/message.dart
- lib/pages/messagesList.dart
- lib/pages/myProfile.dart
- lib/pages/profile.dart
> More gradient
